name: hussein
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  get:
  flutter_screenutil:
  http:
  shared_preferences:
  url_launcher:
  video_player:
  just_audio:
  dio:
  path_provider:
  permission_handler:
  saver_gallery:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash/
    - assets/images/auth/
    - assets/images/drawer/
    - assets/images/home/